import os
from fastapi import FastAPI
from fastapi.staticfiles import StaticFiles
from fastapi.responses import HTMLResponse
from dotenv import load_dotenv
from app.routes import appointment, voice, phone


load_dotenv()


app = FastAPI(title="Bangla AI Receptionist", docs_url="/docs", redoc_url="/redoc")


app.include_router(appointment.router, prefix="/api")
app.include_router(voice.router)
app.include_router(phone.router, prefix="/api")


# Initialize DB
from app.db import init_db
init_db()


# serve frontend for testing
app.mount("/static", StaticFiles(directory="frontend"), name="static")


@app.get("/")
async def home():
    return {"status":"ok", "message":"Bangla AI Receptionist: visit /static/index.html"}


@app.get("/health")
async def health_check():
    return {"status": "healthy", "timestamp": "2023-12-01T00:00:00Z"}


@app.get("/config.js", response_class=HTMLResponse)
async def frontend_config():
    """Serve dynamic configuration to the frontend"""
    # Get the base URL from the request or environment
    websocket_url = os.environ.get("WEBSOCKET_URL")
    
    if not websocket_url:
        # Default logic based on the host
        websocket_url = "window.location.hostname.includes('railway.app') ? `wss://${window.location.host}/ws/ai` : 'ws://localhost:8000/ws/ai'"
        config_content = f"""
// Dynamic configuration generated by backend
window.WEBSOCKET_URL = {websocket_url};

console.log('WebSocket URL configured:', window.WEBSOCKET_URL);
"""
    else:
        # Use the environment variable
        config_content = f"""
// Dynamic configuration from environment
window.WEBSOCKET_URL = "{websocket_url}";

console.log('WebSocket URL configured from environment:', window.WEBSOCKET_URL);
"""
    
    return HTMLResponse(content=config_content, media_type="application/javascript")